services:
  backend:
    depends_on:
      - db
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    env_file:
      - "backend/.env.development"

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - PORT=80

  db:
    image: mysql:5.7
    expose:
      - '3306'
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: password
    command: --skip-ssl --explicit_defaults_for_timestamp


volumes: {}